// SPDX-License-Identifier: ISC
//
// Copyright (c) 2008, Mukunda Johnson (mukunda@maxmod.org)
// Copyright (c) 2026, Antonio Niño Díaz

/****************************************************************************
 *                ____ ___  ____ __  ______ ___  ____  ____/ /              *
 *               / __ `__ \/ __ `/ |/ / __ `__ \/ __ \/ __  /               *
 *              / / / / / / /_/ />  </ / / / / / /_/ / /_/ /                *
 *             /_/ /_/ /_/\__,_/_/|_/_/ /_/ /_/\____/\__,_/                 *
 *                                                                          *
 ****************************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "defs.h"
#include "mas.h"
#include "mod.h"
#include "s3m.h"
#include "xm.h"
#include "it.h"
#include "gba.h"
#include "nds.h"
#include "log.h"
#include "files.h"
#include "errors.h"
#include "simple.h"
#include "msl.h"
#include "systems.h"
#include "wav.h"
#include "samplefix.h"

int target_system;

bool ignore_sflags;
int PANNING_SEP;

void print_usage(void)
{
    INFO(
        "\n"
        "******************\n"
        "* Maxmod Utility * " VERSION_STRING "\n"
        "******************\n"
        "\n"
        "Usage:\n"
        "  mmutil [options] input files ...\n"
        "\n"
        " Input may be MOD, S3M, XM, IT, and/or WAV\n"
        "\n"
        ".------------.----------------------------------------------------.\n"
        "| Option     | Description                                        |\n"
        "|------------|----------------------------------------------------|\n"
        "| -o<output> | Set output file.                                   |\n"
        "| -h<header> | Set header output file.                            |\n"
        "| -D         | Add list of sample and module names to soundbank.  |\n"
        "| -m         | Output MAS file rather than soundbank.             |\n"
        "| -d         | Use for NDS projects.                              |\n"
        "| -b         | Create test ROM. (use -d for .nds, otherwise .gba) |\n"
        "| -i         | Ignore sample name flags (NDS mode only).          |\n"
        "| -v         | Enable verbose output.                             |\n"
        "| -p         | Set initial panning separation for MOD/S3M.        |\n"
        "| -z         | Export raw WAV data (8-bit format)                 |\n"
        "| -V         | Print version string and exit.                     |\n"
        "`-----------------------------------------------------------------'\n"
        "\n"
        ".-----------------------------------------------------------------.\n"
        "| Sample flags                                                    |\n"
        "|-----------------------------------------------------------------|\n"
        "| Sample flags are strings added to a sample name to modify the   |\n"
        "| sample during conversion. The only work in NDS hardware mixing  |\n"
        "| mode.                                                           |\n"
        "|-----------------------------------------------------------------|\n"
        "| %%o: Used to support the `9xx` command when using the DS         |\n"
        "|     hardware channels for playback. In MOD/XM (maybe others)    |\n"
        "|     you can use a sample offset command to start playing beyond |\n"
        "|     the loop start, and then when the sample hits the loop end  |\n"
        "|     it'll still correctly loop back to the start.               |\n"
        "|-----------------------------------------------------------------|\n"
        "| %%c: Compress the sample using IMA-ADPCM. This only works on NDS |\n"
        "|     in hardware mixer mode.                                     |\n"
        "|-----------------------------------------------------------------|\n"
        "|  #: Normally, samples of a module file don't get their own      |\n"
        "|     definitions in the header file generated by `mmutil`. If    |\n"
        "|     the name of a sample starts with `#`, a definition is       |\n"
        "|     generated.                                                  |\n"
        "`-----------------------------------------------------------------'\n"
        "\n"
        ".-----------------------------------------------------------------.\n"
        "| Examples:                                                       |\n"
        "|-----------------------------------------------------------------|\n"
        "| Create DS soundbank file (soundbank.bin) from input1.xm         |\n"
        "| and input2.it Also output header file (soundbank.h)             |\n"
        "|                                                                 |\n"
        "| mmutil -d input1.xm input2.it -osoundbank.bin -hsoundbank.h     |\n"
        "|-----------------------------------------------------------------|\n"
        "| Create test GBA ROM from two inputs                             |\n"
        "|                                                                 |\n"
        "| mmutil -b input1.mod input2.s3m -oTEST.gba                      |\n"
        "|-----------------------------------------------------------------|\n"
        "| Create test NDS ROM from three inputs                           |\n"
        "|                                                                 |\n"
        "| mmutil -d -b input1.xm input2.s3m testsound.wav -oTEST.nds      |\n"
        "`-----------------------------------------------------------------'\n"
    );
}

void print_version_and_exit(void)
{
    INFO("mmutil " VERSION_STRING "\n");
    exit(EXIT_SUCCESS);
}

void print_error(int err)
{
    switch (err)
    {
        case ERR_INVALID_MODULE:
            ERROR("Invalid module!\n");
            break;
        case ERR_MANYARGS:
            ERROR("Too many arguments!\n");
            break;
        case ERR_NOINPUT:
            ERROR("No input file!\n");
            break;
        case ERR_NOWRITE:
            ERROR("Unable to write file!\n");
            break;
        case ERR_BADINPUT:
            ERROR("Cannot parse input filename!\n");
            break;
    }
}

int GetYesNo(void)
{
    char c = tolower(getchar());

    while (getchar() != '\n');

    while (c != 'y' && c != 'n')
    {
        INFO("Was that a yes? ");
        c = tolower(getchar());
        while (getchar() != '\n');
    }
    return c == 'y' ? 1 : 0;
}

int main(int argc, char *argv[])
{
    char *str_input = NULL;
    char *str_output = NULL;
    char *str_header = NULL;

    MAS_Module mod = { 0 };
    Sample samp = { 0 };

    bool g_flag = false;
    bool m_flag = false;
    bool z_flag = false;

    bool msl_export_dictionary = false;

    int output_size;

    ignore_sflags = false;

    PANNING_SEP = 128;

    //------------------------------------------------------------------------
    // parse arguments
    //------------------------------------------------------------------------

    int number_of_inputs = 0;

    for (int a = 1; a < argc; a++)
    {
        if (argv[a][0] == '-')
        {
            if (argv[a][1] == 'V')
                print_version_and_exit();
            else if (argv[a][1] == 'b')
                g_flag = true;
            else if (argv[a][1] == 'v')
                set_log_level(LOG_VERBOSE);
            else if (argv[a][1] == 'd')
                target_system = SYSTEM_NDS;
            else if (argv[a][1] == 'i')
                ignore_sflags = true;
            else if (argv[a][1] == 'p')
                PANNING_SEP = ((argv[a][2] - '0') * 256) / 9;
            else if (argv[a][1] == 'o')
                str_output = argv[a] + 2;
            else if (argv[a][1] == 'h')
                str_header = argv[a] + 2;
            else if (argv[a][1] == 'm')
                m_flag = true;
            else if (argv[a][1] == 'z')
                z_flag = true;
            else if (argv[a][1] == 'D')
                msl_export_dictionary = true;
        }
        else if (!str_input)
        {
            str_input = argv[a];
            number_of_inputs = 1;
        }
        else
        {
            number_of_inputs++;
        }
    }

    if (number_of_inputs == 0)
    {
        print_usage();
        return 0;
    }

    if (str_output == NULL)
    {
        ERROR("No output file specified with -o\n");
        return -1;
    }

    if (z_flag)
    {
        file_open_read(str_input);
        Sample s;

        Load_WAV(&s, false);

        s.name[0] = '%';
        s.name[1] = 'c';
        s.name[2] = 0;

        FixSample(&s);

        file_close_read();
        file_open_write(str_output);

        for (size_t i = 0; i < s.sample_length; i++)
            write8(((u8 *)s.data)[i]);

        file_close_write();
        INFO("Done\n");
        return 0;
    }

    if (m_flag & g_flag)
    {
        ERROR("-m and -g cannot be combined.\n");
        return -1;
    }

    if (m_flag && number_of_inputs != 1)
    {
        ERROR("-m only supports one input.\n");
        return -1;
    }

    //---------------------------------------------------------------------------
    // m/g generate output target if not given
    //---------------------------------------------------------------------------

    if (m_flag || g_flag)
    {
        if (!str_output)
        {
            if (number_of_inputs == 1)
            {
                if (strlen(str_input) < 4)
                {
                    print_error(ERR_BADINPUT);
                    return -1;
                }

                int strp = strlen(str_input);
                str_output = (char *)malloc(strp + 2);
                strcpy(str_output, str_input);
                strp=strlen(str_output)-1;

                int strpi;
                for (strpi = strp; str_output[strpi] != '.' && strpi != 0; strpi--)
                    ;

                if (strpi == 0)
                {
                    print_error(ERR_BADINPUT);
                    return -1;
                }

                str_output[strpi++] = '.';
                if (!g_flag)
                {
                    str_output[strpi++] = 'm';
                    str_output[strpi++] = 'a';
                    str_output[strpi++] = 's';
                    str_output[strpi++] = 0;
                }
                else
                {
                    if (target_system == SYSTEM_GBA)
                    {
                        str_output[strpi++] = 'g';
                        str_output[strpi++] = 'b';
                        str_output[strpi++] = 'a';
                        str_output[strpi++] = 0;
                    }
                    else if (target_system == SYSTEM_NDS)
                    {
                        str_output[strpi++] = 'n';
                        str_output[strpi++] = 'd';
                        str_output[strpi++] = 's';
                        str_output[strpi++] = 0;
                    }
                    else
                    {
                        // error!
                    }
                }
                str_output[strpi++] = 0;
            }
            else
            {
                ERROR("No output file! (-o option)\n");
                return -1;
            }
        }
    }

    // catch filename too small
    int strl = strlen(str_input);
    if (strl < 4)
    {
        print_error(ERR_BADINPUT);
        return -1;
    }

    if (m_flag)
    {
        if (file_open_read(str_input))
        {
            ERROR("Cannot open %s for reading!\n", str_input);
            return -1;
        }

        int input_type = get_ext(str_input);

        switch (input_type)
        {
            case INPUT_TYPE_MOD:
            {
                if (Load_MOD(&mod))
                {
                    print_error(ERR_INVALID_MODULE);
                    file_close_read();
                    return -1;
                }
                break;
            }

            case INPUT_TYPE_S3M:
            {
                if (Load_S3M(&mod))
                {
                    print_error(ERR_INVALID_MODULE);
                    file_close_read();
                    return -1;
                }
                break;
            }

            case INPUT_TYPE_XM:
            {
                if (Load_XM(&mod))
                {
                    print_error(ERR_INVALID_MODULE);
                    file_close_read();
                    return -1;
                }
                break;
            }

            case INPUT_TYPE_IT:
            {
                if (Load_IT(&mod))
                {
                    // ERROR!
                    print_error(ERR_INVALID_MODULE);
                    file_close_read();
                    return -1;
                }
                break;
            }

            case INPUT_TYPE_WAV:
            {
                if (Load_WAV(&samp, false))
                {
                    print_error(ERR_INVALID_MODULE);
                    file_close_read();
                    return -1;
                }

                // Force saving the sample even if it isn't referenced anywhere
                samp.msl_index = 0xFFFF;

                mod.samp_count = 1;
                mod.samples = (Sample *)malloc(sizeof(Sample));
                memcpy(mod.samples, &samp, sizeof(Sample));

                break;
            }
        }

        file_close_read();

        if (file_exists(str_output))
        {
            INFO("Output file exists! Overwrite? (y/n) ");
            if (!GetYesNo())
            {
                ERROR("Operation Canceled!\n");
                return -1;
            }

            file_delete(str_output);
        }

        if (file_open_write(str_output))
        {
            print_error(ERR_NOWRITE);
            return -1;
        }

        INFO("Writing .mas............\n");

        // output MAS
        output_size = Write_MAS(&mod, false);

        file_close_write();

        Delete_Module(&mod);

#ifdef SUPER_ASCII
        VERBOSE("Success! \x02\n");
#else
        VERBOSE("Success! :)\n");
#endif
    }
    else if (g_flag)
    {
        if (file_exists(str_output))
        {
            INFO("Output file exists! Overwrite? (y/n) ");
            if (!GetYesNo())
            {
                ERROR("Operation Canceled!\n");
                return -1;
            }

            file_delete(str_output);
        }

        if (target_system == SYSTEM_GBA)
        {
            MSL_Create(argv, argc, "tempSH308GK.bin", 0, msl_export_dictionary);

            if (file_open_write(str_output))
            {
                print_error(ERR_NOWRITE);
                return -1;
            }

            VERBOSE("Making GBA ROM.......\n");

            Write_GBA();

            output_size = file_size("tempSH308GK.bin");
            file_open_read("tempSH308GK.bin");

            for (int i = 0; i < output_size; i++)
            {
                write8(read8());
            }

            file_close_read();
            file_close_write();

            file_delete("tempSH308GK.bin");

            INFO("Success! :D\n");

            if (output_size < 262144)
                INFO("ROM can be multibooted!!\n");
        }
        else if (target_system == SYSTEM_NDS)
        {
            Write_NDS(argc, argv, str_output, msl_export_dictionary);
        }
        else
        {
            ERROR("Invalid target system!\n");
            return -1;
        }
    }
    else
    {
        MSL_Create(argv, argc, str_output, str_header, msl_export_dictionary);
    }

    return 0;
}
